#version 450
layout (local_size_x = 16) in;

layout(binding = 0) buffer Product {
    float product[];
};

layout(binding = 1) readonly buffer Scalars {
    float scalars[];
};

layout(push_constant) uniform Consts {
    uint scalar_layer_size;
};

void main() {
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= scalars.length()) return;
    for (uint l = 0; l < scalars.length() / scalar_layer_size; l++)
        product[gid] *= scalars[gid + scalar_layer_size * l];
}
